aaa

diff --git a/lib/bats/assertion-test-helpers b/lib/bats/assertion-test-helpers
--- a/lib/bats/assertion-test-helpers
+++ b/lib/bats/assertion-test-helpers
@@ -187,7 +187,7 @@ __expect_assertion_success() {
     "#   \`failing_assertion' failed")
 
   if ! __check_expected_output "$output" "${expected_output[@]}"; then
-    printf "$ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE\n" "${assertion%% *}" >&2
+    printf "$ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE" "${assertion%% *}" >&2
     return '1'
   fi
 }
@@ -230,7 +230,7 @@ __expect_assertion_failure() {
     "${@/#/# }")
 
   if ! __check_expected_output "$output" "${expected_output[@]}"; then
-    printf "$ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE\n" "${assertion%% *}" >&2
+    printf "$ASSERTION_TEST_SCRIPT_FAILURE_MESSAGE" "${assertion%% *}" >&2
     return '1'
   fi
 }
@@ -271,8 +271,7 @@ __run_command_and_assertion_in_subshell() {
   __assertion_output="${__assertion_output%$'\n'}"
 
   if [[ "$__assertion_output" =~ write\ error:\ Bad\ file\ descriptor$ ]]; then
-    printf \
-      "'%s' tried to write to standard output instead of standard error\n" \
+    printf "'%s' tried to write to standard output instead of standard error" \
       "${assertion%% *}" >&2
     return 1
   elif [[ -z "$__assertion_status" ]]; then
diff --git a/libexec/env b/libexec/env
--- a/libexec/env
+++ b/libexec/env
@@ -21,15 +21,15 @@ _@go.has_spaces() {
 
 _@go.env() {
   # Tab completions
-  if [[ "$1" == '--complete' ]]; then
+  if [[ "${1-}" == '--complete' ]]; then
     local word_index="$2"
     if [[ "$word_index" -eq '0' ]]; then
       echo '-'
     fi
-    return
+    return "$_GO_EC_OK"
   fi
 
-  local go_func="$1"
+  local go_func="${1-}"
   local default_name="${_GO_SCRIPT##*/}"
   local shell="${SHELL##*/}"
   local shell_impl="$_GO_CORE_DIR/lib/internal/env/$shell"
@@ -39,7 +39,7 @@ _@go.env() {
     @go.printf "%s%s\n" \
       "Check $_GO_CORE_URL/tree/master/lib/env to see if an implementation " \
       "has been added, or feel free to send a pull request to add it." >&2
-    return 1
+    return "$_GO_EC_GENERR"
   fi
 
   local spaces_error=('ERROR: %s must not contain spaces in order'
@@ -47,7 +47,7 @@ _@go.env() {
 
   if _@go.has_spaces "$default_name"; then
     @go.printf "${spaces_error[*]}" "the \"$default_name\" script" >&2
-    return 1
+    return "$_GO_EC_CONFIG"
   fi
 
   if [[ -z "$go_func" ]]; then
@@ -67,15 +67,22 @@ _@go.env() {
       @go.printf 'ERROR: %s must contain a line of the form "%s" %s%s\n' \
         "$shell_impl" "$eval_pattern" "illustrating the command used to " \
         "evaluate the generated shell commands." >&2
-      return 1
+      return "$_GO_EC_BADFRMT"
     fi
 
-    read -r -d '' help_msg <<END_OF_HELP
+    read -r -d '' help_msg <<END_OF_HELP && exit_code=0 || exit_code=$?
 # Define the "$default_name" function by running the following command.
 # Replace '-' to use a different name instead of "$default_name".
 
 ${eval_cmd//%s/$0}
 END_OF_HELP
+
+    if [[ "$exit_code" -gt 1 ]]; then
+      # Due to encountering EOL, 'read' will return with '1'. To support 'set -e'
+      # we only return the exit code if an actual error has occured ($? -gt 1).
+      return $exit_code
+    fi
+
     @go.printf "$help_msg\n"
     return
   elif [[ "$go_func" == '-' ]]; then
@@ -84,10 +91,14 @@ END_OF_HELP
 
   if _@go.has_spaces "$go_func"; then
     @go.printf "${spaces_error[*]}" "\"$go_func\"" >&2
-    return 1
+    return "$_GO_EC_CONFIG"
   fi
 
-  read -r -d '' env_script < "$shell_impl"
+  read -r -d '' env_script < "$shell_impl" && exit_code=0 || exit_code=$?
+  if [[ "$exit_code" -gt 1 ]]; then
+    return $exit_code
+  fi
+
   env_script="${env_script//_go_func/$go_func}"
   env_script="${env_script//\$_GO_ROOTDIR/$_GO_ROOTDIR}"
   echo "${env_script//\$_GO_SCRIPT/$_GO_SCRIPT}"
